ALTER TABLE dev.Flow MODIFY COLUMN IDFlow INT NOT NULL AUTO_INCREMENT;

ALTER TABLE dev.Flow DROP FOREIGN KEY FK_IDForm;
ALTER TABLE dev.Form MODIFY COLUMN IDForm INT NOT NULL AUTO_INCREMENT;
ALTER TABLE dev.Flow ADD CONSTRAINT FK_IDForm FOREIGN KEY (IDForm) REFERENCES dev.Form(IDForm);

ALTER TABLE dev.frm_PR_D MODIFY COLUMN IDItem INT NOT NULL AUTO_INCREMENT;

ALTER TABLE dev.frm_PR_H MODIFY COLUMN ID INT NOT NULL AUTO_INCREMENT;

ALTER TABLE dev.frm_PR_NoPR MODIFY COLUMN ID INT NOT NULL AUTO_INCREMENT;

ALTER TABLE dev.Flow DROP FOREIGN KEY FK2_IDSection;
ALTER TABLE dev.UserMaster DROP FOREIGN KEY IDSection;
ALTER TABLE dev.Form DROP FOREIGN KEY FK_IDSection;
ALTER TABLE dev.Section MODIFY COLUMN IDSection INT NOT NULL AUTO_INCREMENT;
ALTER TABLE dev.Form ADD CONSTRAINT FK_IDSection FOREIGN KEY (IDSection) REFERENCES dev.Section(IDSection);
ALTER TABLE dev.UserMaster ADD CONSTRAINT IDSection FOREIGN KEY (IDSection) REFERENCES dev.Section(IDSection);
ALTER TABLE dev.Flow ADD CONSTRAINT FK2_IDSection FOREIGN KEY (IDSection) REFERENCES dev.Section(IDSection);

ALTER TABLE dev.UserMaster DROP FOREIGN KEY IDTitle;
ALTER TABLE dev.Title MODIFY COLUMN IDTitle INT NOT NULL AUTO_INCREMENT;
ALTER TABLE dev.UserMaster ADD CONSTRAINT IDTitle FOREIGN KEY (IDTitle) REFERENCES dev.Title(IDTitle);

ALTER TABLE dev.Trace_D DROP FOREIGN KEY IDTrace;
SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';
UPDATE Trace 
SET SubmitDate = NULL 
WHERE SubmitDate = '0000-00-00 00:00:00' 
   OR SubmitDate = '0000-00-00';
SET SESSION sql_mode = 'IGNORE_SPACE,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
ALTER TABLE dev.Trace MODIFY COLUMN IDTrace INT NOT NULL AUTO_INCREMENT;
ALTER TABLE dev.Trace_D ADD CONSTRAINT IDTrace FOREIGN KEY (IDTrace) REFERENCES dev.Trace(IDTrace);

ALTER TABLE dev.Form DROP FOREIGN KEY FK_IDType;
ALTER TABLE dev.Type MODIFY COLUMN IDType INT NOT NULL AUTO_INCREMENT;
ALTER TABLE dev.Form ADD CONSTRAINT FK_IDType FOREIGN KEY (IDType) REFERENCES dev.Type(IDType);

ALTER TABLE dev.UploadFile MODIFY COLUMN IDUpload INT NOT NULL AUTO_INCREMENT;

ALTER TABLE dev.Trace_D DROP FOREIGN KEY IDUser;
ALTER TABLE dev.Flow DROP FOREIGN KEY FK_IDUser;
ALTER TABLE dev.UserMaster MODIFY COLUMN IDUser INT NOT NULL AUTO_INCREMENT;
ALTER TABLE dev.Flow ADD CONSTRAINT FK_IDUser FOREIGN KEY (IDUser) REFERENCES dev.UserMaster(IDUser);
ALTER TABLE dev.Trace_D ADD CONSTRAINT IDUser FOREIGN KEY (IDUser) REFERENCES dev.UserMaster(IDUser);