/**
 * Splits a string format of a date generated by HTML Input element of type `date`
 * @param dateString string of a date (e.g "24-02-2026")
 * @returns year, month, and day of the string date
 */

export const dateSplitter = (
  dateString: string,
): [y: string, m: string, d: string] => {
  const [year, month, day] = dateString.split("-");
  return [year, month, day];
};
